export default {
    START_FETCH_BLOG_LIST:'START_FETCH_BLOG_LIST', //开始请求blog_list
    FETCH_BLOG_LIST_SUCCESS:'FETCH_BLOG_LIST_SUCCESS' ,//请求成功
    FETCH_BLOG_LIST_FAILED:'FETCH_BLOG_LIST_FAILED', //请求失败
}